spring:
  profiles:
    active: test
---
# Test profile yml
spring:
  profiles: test
  datasource:
    url: jdbc:h2:mem:testdb
  jpa:
    show-sql : true
    properties:
      hibernate:
        generate_statistics : true

---
# Production profile yml
spring:
  profiles:
    prod