spring:
  profiles:
    active: test
---
# Test profile yml
spring:
  profiles: test
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:testdb

# # debugging sql com
#  jpa:
#    show-sql : true
#    properties:
#      hibernate:
#        generate_statistics : true

# # debugging security
logging:
  level:
    org:
      springframework:
        security: debug
    sena:
      activitytracker:
        acktrack: debug

# Security replaced with overriden UserDetails service
#  security:
#    user:
#      name: user
#      password: user
---
# Production profile yml
spring:
  profiles:
    prod