package sena.activitytracker.acktrack.mappers;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import sena.activitytracker.acktrack.dtos.ActivityDTO;
import sena.activitytracker.acktrack.model.Activity;
import sena.activitytracker.acktrack.model.Issue;
import sena.activitytracker.acktrack.model.Workpackage;

import java.util.HashSet;
import java.util.Set;

public abstract class ActivityMapperDecorator implements ActivityMapper{

    private ActivityMapper activityMapper;

    /* Documentation: https://mapstruct.org/documentation/1.0/api/org/mapstruct/DecoratedWith.html */
    @Autowired
    @Qualifier("delegate")
    public void setActivityMapper(ActivityMapper activityMapper){
        this.activityMapper = activityMapper;
    }

    @Override
    public ActivityDTO toActivityDTO(Activity activity) {

        /*Trigger first: assembler generated by mapstruct*/
        ActivityDTO activityDTO = activityMapper.toActivityDTO(activity);

        /* fill in missing properties*/
        /* user name */
        String userName = assembleUserName(activity);
        if( userName != null)  activityDTO.setUserName(userName);
        /* workpackage ids*/
        activityDTO.setWorkpackageIds(assembleworkpackageIds(activity.getWorkpackages()));
        /* issue ids */
        activityDTO.setIssueIds(assembleIssueIds(activity.getIssues()));

        return activityDTO;
    }

    /*
    * Assembling Methods:
    * */
    private String assembleUserName(Activity activity){

        String name = null;

        if( activity.getUser()!=null &&
            activity.getUser().getFamilyName() != null &&
            activity.getUser().getGivenName() != null){

            name = activity.getUser().getGivenName() +
                   ", " +
                   activity.getUser().getFamilyName();
        }

        return name;
    }

    private Set<String> assembleworkpackageIds(Set<Workpackage> workpackages){

        Set<String> wpids = new HashSet<>();

        if( workpackages !=null){
            workpackages.forEach(workpackage -> wpids.add(workpackage.getName()));
        }

        return wpids;
    }

    private Set<String> assembleIssueIds(Set<Issue> issues){

        Set<String> issueIds = new HashSet<>();

        if( issues !=null){
            issues.forEach(issue -> issueIds.add(issue.getIssue_id()));
        }

        return issueIds;
    }
}
