package sena.activitytracker.acktrack.mappers;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import sena.activitytracker.acktrack.dtos.ActivityDTO;
import sena.activitytracker.acktrack.model.Activity;

public abstract class ActivityMapperDecorator implements ActivityMapper{

    private ActivityMapper activityMapper;

    /* Documentation: https://mapstruct.org/documentation/1.0/api/org/mapstruct/DecoratedWith.html */
    @Autowired
    @Qualifier("delegate")
    public void setActivityMapper(ActivityMapper activityMapper){
        this.activityMapper = activityMapper;
    }

    @Override
    public ActivityDTO toActivityDTO(Activity activity) {

        /*Trigger first: assembler generated by mapstruct*/
        ActivityDTO activityDTO = activityMapper.toActivityDTO(activity);

        /* fill in missing properties*/
        /* user name */
        String userName = assembleUserName(activity);
        if( userName != null)  activityDTO.setUserName(userName);

        return activityDTO;
    }

    /*
    * Assembling Methods:
    * */
    private String assembleUserName(Activity activity){

        String name = null;

        if( activity.getUser()!=null &&
            activity.getUser().getFamilyName() != null &&
            activity.getUser().getGivenName() != null){

            name = activity.getUser().getGivenName() +
                   ", " +
                   activity.getUser().getFamilyName();
        }

        return name;
    }
}
